collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  lightness: 0
  brandStrength: 0
  brandColors:
    - '#542E1E'
    - '#FFFB9A'
    - '#FFFA02'
    - '#A3A4A3'
    - '#0288E9'
  rhythmicContrast: 0
typography_spectrum: 0.02553191
layout_spectrum: 0.1638298
name: Johnny Glucose
