name: Johnny Glucose
favicon: null
layout_spectrum: 0.54792
typography_spectrum: 0.54985
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Johnny Glucose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#460907'
    - '#69367a'
    - '#987783'
    - '#88a0b9'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
