name: Johnny Glucose
favicon: null
layout_spectrum: 0.54792
typography_spectrum: 0.54985
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Johnnys GlueClose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#542E1E'
    - '#FFFB9A'
    - '#FFFA02'
    - '#A3A4A3'
    - '#0288E9'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
